### ISSUE TITLE
Better document the license under which this code is released

### ISSUE THREAD

**Issue by ryandesign** [gnosek/fcgiwrap#23]
I see in the comment header in the file fcgiwrap.c that this is under the MIT license, but it would be easier to find this information if you mentioned the license on the project's homepage and in the README, and if you had the license text in a file named LICENSE or COPYING.

**Comment by gnosek** [comment]
Added the relevant info:

https://github.com/gnosek/fcgiwrap/commit/b6696a1495dc818d0b22d9c2e9be7c618e25b3af

Thanks.
