### ISSUE TITLE
problem compilling

### ISSUE THREAD

**Issue by cybernet** [gnosek/fcgiwrap#9]
Ubuntu Lucid
autoconf (GNU Autoconf) 2.65

git clone https://github.com/gnosek/fcgiwrap.git

cd fcgiwrap

autoconf

configure.ac:32: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:39: error: possibly undefined macro: AM_CONDITIONAL

**Comment by cybernet** [comment]
i can't believe i used my own bug report to fix the same problem

thanks @animhotep

**Comment by justinclift** [comment]
Just made a PR, so it gets added to the requirements in the README: https://github.com/gnosek/fcgiwrap/pull/27

Hopefully that helps someone. :smile:

**Comment by cybernet** [comment]
+1
